name: Build and Update Resources

permissions:
  contents: write

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build BrowseBot (dev for both files)
        run: |
          npx cross-env TARGET=browsebot BUILD_TYPE=dev rollup -c --bundleConfigAsCjs

      - name: Combine Preferences
        run: npm run combine-preferences

      - name: Commit BrowseBot changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: Update browsebot build"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com"
          file_pattern: "dist/browse-bot*.uc.*"

      - name: Commit preferences changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: Update combined preferences"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com"
          file_pattern: "preferences.json"
