name: Update and Build Resources

permissions:
  contents: write

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update_and_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Grant read permissions
        run: find . -name "theme.json" -print0 | xargs -0 chmod a+r

      - name: Update theme.json files
        id: update_theme
        run: |
          node .github/scripts/update-theme.js
          echo "updated=$?" >> $GITHUB_OUTPUT

      - name: Commit theme.json changes
        if: steps.update_theme.outputs.updated == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add **/theme.json
          git diff --cached --quiet || git commit -m "chore: Update theme.json"

      - name: Build BrowseBot (dev for both files)
        run: |
          npx cross-env TARGET=browsebot BUILD_TYPE=dev rollup -c --bundleConfigAsCjs

      - name: Combine Preferences
        run: npm run combine-preferences

      - name: Commit BrowseBot changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add dist/browse-bot*.uc.*
          git diff --cached --quiet || git commit -m "chore: Update browsebot build"

      - name: Commit preferences changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add preferences.json
          git diff --cached --quiet || git commit -m "chore: Update combined preferences"

      - name: Run Prettier
        run: npm run format

      - name: Commit formatting changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git diff --cached --quiet || git commit -m "chore: Auto format"

      - name: Fetch latest changes
        run: git fetch origin ${{ github.ref_name || 'main' }}

      - name: Push all changes
        run: git push origin ${{ github.ref_name || 'main' }}